"""Contract-level tests; cryptographic checks require the real cluster demo."""

import importlib.util
import unittest
from pathlib import Path

MODULE = Path(__file__).resolve().parents[2] / "policies" / "kyverno" / "render.py"
SPEC = importlib.util.spec_from_file_location("kyverno_render", MODULE)
renderer = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(renderer)


class RenderTests(unittest.TestCase):
    def config(self, mode="local"):
        return {
            "mode": mode, "repository": "https://github.com/example/laboratory",
            "commit": "a" * 40, "image_repository": "registry.example/quotes-node",
            "sbom_version": "1.6", "policy_version": "golden-path-v1",
            # This synthetic PEM is never used for cryptographic verification.
            "public_key": "-----BEGIN PUBLIC KEY-----\nSYNTHETIC\n-----END PUBLIC KEY-----\n",
            "identity": "https://github.com/example/laboratory/.github/workflows/golden-path.yml@refs/heads/main",
        }

    def test_every_barrier_is_distinct_and_fail_closed(self):
        items = renderer.render(self.config())["items"]
        self.assertEqual([p["metadata"]["name"] for p in items], [
            "tfm-runtime", "tfm-signature", "tfm-sbom", "tfm-provenance", "tfm-results"])
        for item in items:
            self.assertEqual(item["spec"]["failurePolicy"], "Fail")
            self.assertEqual(item["spec"]["validationFailureAction"], "Enforce")
            self.assertEqual(item["metadata"]["annotations"]["pod-policies.kyverno.io/autogen-controllers"], "Deployment")
            for rule in item["spec"]["rules"]:
                resources = rule["match"]["any"][0]["resources"]
                self.assertEqual(resources["namespaces"], ["tfm-golden"])
                self.assertEqual(resources["operations"], ["CREATE", "UPDATE"])
                self.assertNotIn("selector", resources)

    def test_no_mutation_or_implicit_image_verification(self):
        for item in renderer.render(self.config())["items"][1:]:
            check = item["spec"]["rules"][0]["verifyImages"][0]
            self.assertFalse(check["mutateDigest"])
            self.assertTrue(check["verifyDigest"])
            self.assertTrue(check["required"])
            self.assertEqual(check["imageReferences"], ["registry.example/quotes-node@sha256:*"])

    def test_ephemeral_rejection_cannot_block_autogenerated_deployments(self):
        runtime = renderer.render(self.config())["items"][0]
        rule = next(rule for rule in runtime["spec"]["rules"] if rule["name"] == "no-ephemeral-debug-containers")
        self.assertEqual(rule["preconditions"], {"all": [{
            "key": "{{ request.subResource || '' }}", "operator": "Equals", "value": "ephemeralcontainers",
        }]})

    def test_github_provenance_uses_native_bundle_and_exact_identity(self):
        config = self.config("github")
        config["registry_secret"] = "gp-ghcr"
        items = renderer.render(config)["items"]
        check = items[3]["spec"]["rules"][0]["verifyImages"][0]
        self.assertEqual(check["type"], "SigstoreBundle")
        attestation = check["attestations"][0]
        self.assertEqual(attestation["type"], "https://slsa.dev/provenance/v1")
        self.assertNotIn("predicateType", attestation)
        keyless = attestation["attestors"][0]["entries"][0]["keyless"]
        self.assertEqual(keyless["subject"], config["identity"])
        self.assertNotIn("ignoreTlog", keyless["rekor"])
        self.assertEqual(check["imageRegistryCredentials"]["secrets"], ["gp-ghcr"])

    def test_result_contract_checks_every_required_control(self):
        item = renderer.render(self.config())["items"][-1]
        rule = item["spec"]["rules"][0]
        self.assertEqual(rule["name"], "require-results")
        attestation = rule["verifyImages"][0]["attestations"][0]
        self.assertEqual(attestation["predicateType"], renderer.RESULTS_TYPE)
        checks = attestation["conditions"][0]["all"]
        self.assertEqual(len(checks), 4 + len(renderer.CHECKS))
        for name in renderer.CHECKS:
            self.assertIn(renderer.condition("checks." + name, "PASS"), checks)

    def test_local_provenance_does_not_claim_github_builder(self):
        item = renderer.render(self.config())["items"][3]
        check = item["spec"]["rules"][0]["verifyImages"][0]
        self.assertEqual(check["type"], "Cosign")
        conditions = check["attestations"][0]["conditions"][0]["all"]
        self.assertIn(renderer.condition("buildDefinition.buildType", "https://tfm-goldenpath.dev/buildtypes/local/v1"), conditions)

    def test_trust_parameters_cannot_include_wildcards(self):
        for field, value in [("image_repository", "registry.example/*"), ("commit", "main"), ("sbom_version", "latest"), ("identity", "https://github.com/example/laboratory/.github/workflows/*@refs/heads/main")]:
            with self.subTest(field=field):
                config = self.config("github")
                config[field] = value
                with self.assertRaises(ValueError):
                    renderer.render(config)

    def test_repository_rejects_tags_but_allows_registry_ports(self):
        for repository in ["registry.example/quotes-node:latest", "quotes-node:v1", "registry.example:5000/quotes-node:v1"]:
            config = self.config()
            config["image_repository"] = repository
            with self.assertRaises(ValueError):
                renderer.render(config)
        config = self.config()
        config["image_repository"] = "registry.example:5000/quotes-node"
        self.assertEqual(len(renderer.render(config)["items"]), 5)


if __name__ == "__main__":
    unittest.main()
