"""Contract-level tests; cryptographic checks require the real cluster demo."""

import importlib.util
import re
import unittest
from pathlib import Path

MODULE = Path(__file__).resolve().parents[2] / "policies" / "kyverno" / "render.py"
SPEC = importlib.util.spec_from_file_location("kyverno_render", MODULE)
renderer = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(renderer)


class RenderTests(unittest.TestCase):
    def config(self, mode="local"):
        return {
            "mode": mode, "repository": "https://github.com/example/laboratory",
            "commit": "a" * 40, "image_repository": "registry.example/quotes-node",
            "sbom_version": "1.7", "policy_version": "golden-path-v1",
            # This synthetic PEM is never used for cryptographic verification.
            "public_key": "-----BEGIN PUBLIC KEY-----\nSYNTHETIC\n-----END PUBLIC KEY-----\n",
            "identity": "https://github.com/example/laboratory/.github/workflows/golden-path.yml@refs/heads/main",
        }

    def test_only_supported_sbom_version_is_rendered(self):
        for version in ("1.6", "1.8", "1.99"):
            config = self.config()
            config["sbom_version"] = version
            with self.assertRaises(ValueError):
                renderer.render(config)

    def test_every_barrier_is_distinct_and_fail_closed(self):
        for mode in ("local", "github"):
            items = renderer.render(self.config(mode))["items"]
            self.assertEqual([p["metadata"]["name"] for p in items], [
                "tfm-runtime", "tfm-signature", "tfm-sbom", "tfm-provenance", "tfm-results"])
            for item in items:
                with self.subTest(mode=mode, policy=item["metadata"]["name"]):
                    self.assertEqual(item["apiVersion"], "kyverno.io/v1")
                    self.assertEqual(item["kind"], "ClusterPolicy")
                    self.assertFalse(item["spec"]["background"])
                    self.assertEqual(item["spec"]["failurePolicy"], "Fail")
                    self.assertEqual(item["spec"]["validationFailureAction"], "Enforce")
                    self.assertEqual(item["spec"]["webhookTimeoutSeconds"], 30)
                    self.assertEqual(item["metadata"]["annotations"]["pod-policies.kyverno.io/autogen-controllers"], "Deployment")
                    for rule in item["spec"]["rules"]:
                        kind = "Pod/ephemeralcontainers" if rule["name"] == "no-ephemeral-debug-containers" else "Pod"
                        self.assertEqual(rule["match"], {"any": [{"resources": {
                            "kinds": [kind], "namespaces": ["tfm-golden"], "operations": ["CREATE", "UPDATE"],
                        }}]})
                        self.assertNotIn("exclude", rule)

    def test_no_mutation_or_implicit_image_verification(self):
        for mode in ("local", "github"):
            for item in renderer.render(self.config(mode))["items"][1:]:
                with self.subTest(mode=mode, policy=item["metadata"]["name"]):
                    check = item["spec"]["rules"][0]["verifyImages"][0]
                    self.assertFalse(check["mutateDigest"])
                    self.assertTrue(check["verifyDigest"])
                    self.assertTrue(check["required"])
                    self.assertEqual(check["imageReferences"], ["registry.example/quotes-node@sha256:*"])

    def test_ephemeral_rejection_cannot_block_autogenerated_deployments(self):
        runtime = renderer.render(self.config())["items"][0]
        rule = next(rule for rule in runtime["spec"]["rules"] if rule["name"] == "no-ephemeral-debug-containers")
        self.assertEqual(rule["preconditions"], {"all": [{
            "key": "{{ request.subResource || '' }}", "operator": "Equals", "value": "ephemeralcontainers",
        }]})

    def test_registry_credentials_reach_every_bundle_verifier(self):
        for mode in ("local", "github"):
            config = self.config(mode)
            for secret in (None, "gp-ghcr"):
                config["registry_secret"] = secret
                for item in renderer.render(config)["items"][1:]:
                    check = item["spec"]["rules"][0]["verifyImages"][0]
                    if secret:
                        self.assertEqual(check["imageRegistryCredentials"], {"secrets": [secret]})
                    else:
                        self.assertNotIn("imageRegistryCredentials", check)

    def test_results_requirement_cannot_be_downgraded_to_fixture_policy(self):
        config = self.config()
        config['policy_version'] = 'laboratory-results-p0-fixture'
        with self.assertRaises(ValueError):
            renderer.render(config)

    def test_result_contract_checks_every_required_control(self):
        for mode in ("local", "github"):
            config = self.config(mode)
            item = renderer.render(config)["items"][-1]
            rule = item["spec"]["rules"][0]
            self.assertEqual(rule["name"], "require-results")
            attestation = rule["verifyImages"][0]["attestations"][0]
            self.assertEqual(attestation["type"], renderer.RESULTS_TYPE)
            expected = [
                ("policyVersion", "golden-path-v1"), ("source.repository", config["repository"]),
                ("source.commit", config["commit"]), ("result", "PASS"),
                *[("checks." + name, "PASS") for name in (
                    "unitTests", "manifestPolicy", "workflowPolicy", "vulnerabilityPolicy", "signature", "sbom", "provenance",
                )],
            ]
            self.assertEqual(attestation["conditions"], [{"all": [renderer.condition(key, value, "RESULTS_POLICY_VERSION" if key == "policyVersion" else None) for key, value in expected]}])

    def test_every_evidence_type_uses_bundle_and_explicit_predicate(self):
        expected = [
            "https://sigstore.dev/cosign/sign/v1", "https://cyclonedx.org/bom",
            "https://slsa.dev/provenance/v1", "https://tfm-goldenpath.dev/attestations/verification-results/v1",
        ]
        for mode in ("local", "github"):
            config = self.config(mode)
            for item, predicate in zip(renderer.render(config)["items"][1:], expected):
                with self.subTest(mode=mode, policy=item["metadata"]["name"]):
                    check = item["spec"]["rules"][0]["verifyImages"][0]
                    self.assertEqual(check["type"], "SigstoreBundle")
                    self.assertNotIn("attestors", check)
                    self.assertEqual(len(check["attestations"]), 1)
                    attestation = check["attestations"][0]
                    self.assertEqual(attestation["type"], predicate)
                    self.assertNotIn("predicateType", attestation)

    def test_local_timestamp_exceptions_never_reach_hosted_trust(self):
        for mode in ("local", "github"):
            config = self.config(mode)
            for item in renderer.render(config)["items"][1:]:
                with self.subTest(mode=mode, policy=item["metadata"]["name"]):
                    attestation = item["spec"]["rules"][0]["verifyImages"][0]["attestations"][0]
                    if mode == "github":
                        trust = {"keyless": {
                            "subject": config["identity"], "issuer": "https://token.actions.githubusercontent.com",
                            "rekor": {"url": "https://rekor.sigstore.dev"},
                        }}
                    else:
                        trust = {"keys": {
                            "publicKeys": config["public_key"], "rekor": {"ignoreTlog": True}, "ctlog": {"ignoreSCT": True},
                        }}
                    self.assertEqual(attestation["attestors"], [{"count": 1, "entries": [trust]}])

    def test_image_signature_is_required_independently_of_other_attestations(self):
        # Contract regression for F07: the predicate selected for image signing
        # must be absent when only the other three signed statements are present.
        # This checks policy construction; the hosted scenario verifies admission.
        other_predicates = {renderer.SBOM_TYPE, renderer.PROVENANCE_TYPE, renderer.RESULTS_TYPE}
        for mode in ("local", "github"):
            signature = renderer.render(self.config(mode))["items"][1]
            rule = signature["spec"]["rules"][0]
            self.assertEqual(rule["name"], "require-image-signature")
            self.assertNotIn("preconditions", rule)
            check = rule["verifyImages"][0]
            predicates = {entry["type"] for entry in check["attestations"]}
            self.assertEqual(predicates, {"https://sigstore.dev/cosign/sign/v1"})
            self.assertFalse(predicates & other_predicates)
            self.assertNotIn("conditions", check["attestations"][0])

    def test_provenance_checks_builder_repository_and_commit_in_both_modes(self):
        for mode, builder in (
            ("local", "https://tfm-goldenpath.dev/buildtypes/local/v1"),
            ("github", "https://actions.github.io/buildtypes/workflow/v1"),
        ):
            config = self.config(mode)
            item = renderer.render(config)["items"][3]
            attestation = item["spec"]["rules"][0]["verifyImages"][0]["attestations"][0]
            self.assertEqual(attestation["conditions"], [{"all": [
                renderer.condition("buildDefinition.buildType", builder, "PROVENANCE_BUILD_TYPE"),
                renderer.condition("buildDefinition.externalParameters.workflow.repository", config["repository"], "PROVENANCE_REPOSITORY"),
                renderer.condition("buildDefinition.resolvedDependencies[0].digest.gitCommit", config["commit"], "PROVENANCE_REVISION"),
                renderer.condition("runDetails.builder.id", config["identity"] if mode == "github" else "https://tfm-goldenpath.dev/builders/local-development", "PROVENANCE_BUILDER"),
            ]}])

    def test_sbom_keeps_generated_format_and_version_requirements(self):
        for mode in ("local", "github"):
            config = self.config(mode)
            item = renderer.render(config)["items"][2]
            attestation = item["spec"]["rules"][0]["verifyImages"][0]["attestations"][0]
            self.assertEqual(attestation["conditions"], [{"all": [
                renderer.condition("bomFormat", "CycloneDX"), renderer.condition("specVersion", "1.7"),
            ]}])

    def test_runtime_rules_still_cover_all_container_types_and_host_access(self):
        runtime = renderer.render(self.config())["items"][0]
        rules = {rule["name"]: rule for rule in runtime["spec"]["rules"]}
        self.assertEqual(rules["restricted-runtime"]["validate"]["pattern"]["spec"], {
            "=(hostNetwork)": False, "=(hostPID)": False, "=(hostIPC)": False,
            "securityContext": {"seccompProfile": {"type": "RuntimeDefault"}},
        })
        containers = rules["restricted-containers"]["validate"]["foreach"][0]
        self.assertEqual(containers["list"], "request.object.spec.[containers, initContainers, ephemeralContainers][]")
        self.assertEqual(containers["pattern"]["securityContext"], {
            "privileged": False, "allowPrivilegeEscalation": False, "runAsNonRoot": True,
            "readOnlyRootFilesystem": True, "capabilities": {"drop": ["ALL"], "X(add)": "null"},
        })
        images = rules["authorized-image-repository"]["validate"]["foreach"][0]
        self.assertEqual(images["list"], containers["list"])
        deny = images["deny"]["conditions"]["all"][0]
        self.assertEqual(deny["operator"], "Equals")
        self.assertIs(deny["value"], False)
        regex = re.fullmatch(r"\{\{ regex_match\('(.+)', element.image\) \}\}", deny["key"]).group(1)
        image = "registry.example/quotes-node@sha256:" + "b" * 64
        self.assertIsNotNone(re.fullmatch(regex, image))
        for invalid in (image.replace("registry.example", "registryXexample"), image + "f", image[:-1], "registry.example/quotes-node:latest", "untrusted.example/quotes-node@sha256:" + "b" * 64):
            self.assertIsNone(re.fullmatch(regex, invalid))
        self.assertEqual(rules["no-host-path"]["validate"]["foreach"], [
            {"list": "request.object.spec.volumes || `[]`", "pattern": {"X(hostPath)": "null"}},
        ])
        self.assertEqual(rules["no-ephemeral-debug-containers"]["validate"]["deny"], {})

    def test_trust_parameters_cannot_include_wildcards(self):
        for field, value in [("image_repository", "registry.example/*"), ("commit", "main"), ("sbom_version", "latest"), ("identity", "https://github.com/example/laboratory/.github/workflows/*@refs/heads/main")]:
            with self.subTest(field=field):
                config = self.config("github")
                config[field] = value
                with self.assertRaises(ValueError):
                    renderer.render(config)

    def test_repository_rejects_tags_but_allows_registry_ports(self):
        for repository in ["registry.example/quotes-node:latest", "quotes-node:v1", "registry.example:5000/quotes-node:v1"]:
            config = self.config()
            config["image_repository"] = repository
            with self.assertRaises(ValueError):
                renderer.render(config)
        config = self.config()
        config["image_repository"] = "registry.example:5000/quotes-node"
        self.assertEqual(len(renderer.render(config)["items"]), 5)


if __name__ == "__main__":
    unittest.main()
